name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Java
      id: download-java
      uses: typelevel/download-java@v1
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: jdkfile
        java-version: ${{ matrix.java-version }}
        jdkFile: ${{ steps.download-java.outputs.jdkFile }}

    - name: Scalafmt
      run: sbt scalafmtCheckAll scalafmtSbtCheck

    - name: Run tests
      run: |
        sbt headerCheck
        sbt test
        sbt mimaReportBinaryIssues
